'use strict';
const express = require('express');
const approvalService = require('../services/approval-service');
const { validate } = require('../common/validate');
const schemas = require('../schemas/approvals');
function _requireIdentity(req, res) { if (!req.identity || !req.identity.userId) { res.status(401).json({ error: 'actor_user_id_not_in_trusted_context' }); return null; } if (!req.identity.orgId) { res.status(401).json({ error: 'org_id_not_in_trusted_context' }); return null; } return req.identity; }
function _parseIntParam(val, name) { const n = parseInt(val, 10); if (isNaN(n) || n < 1) return { error: 'invalid_' + name }; return { value: n }; }
function _clampPagination(query) { let limit = parseInt(query.limit, 10); let offset = parseInt(query.offset, 10); if (isNaN(limit) || limit < 1) limit = 50; if (limit > 200) limit = 200; if (isNaN(offset) || offset < 0) offset = 0; return { limit, offset }; }
function _mapError(res, result) { const e = result.error; if (e === 'approval_request_not_found') return res.status(404).json({ error: e }); if (e === 'approver_not_authorized' || e === 'self_approval_prohibited') return res.status(403).json({ error: e }); if (typeof e === 'string' && e.startsWith('invalid_transition')) return res.status(409).json({ error: e }); return res.status(400).json({ error: e }); }
function createApprovalRoutes(db) {
    if (!db) throw new Error('[approvals] FATAL: db required for approval routes — fail closed');
    const router = express.Router();
    router.get('/', async (req, res) => { try { const id = _requireIdentity(req, res); if (!id) return; const { limit, offset } = _clampPagination(req.query); const result = await approvalService.listApprovalRequests(db, { org_id: id.orgId, request_status: req.query.status || undefined, target_type: req.query.target_type || undefined, action_key: req.query.action_key || undefined, risk_level: req.query.risk_level || undefined, limit, offset }); if (!result.success) return res.status(500).json({ error: result.error }); return res.json({ success: true, requests: result.requests, total: result.total, limit, offset }); } catch (err) { return res.status(500).json({ error: err.message }); } });
    router.get('/summary', async (req, res) => { try { const id = _requireIdentity(req, res); if (!id) return; const result = await await approvalService.summarizeApprovalRequests(db, id.orgId); if (!result.success) return res.status(500).json({ error: result.error }); return res.json({ success: true, summary: result.summary }); } catch (err) { return res.status(500).json({ error: err.message }); } });
    router.get('/:id', async (req, res) => { try { const id = _requireIdentity(req, res); if (!id) return; const parsed = _parseIntParam(req.params.id, 'id'); if (parsed.error) return res.status(400).json({ error: parsed.error }); const result = await approvalService.getApprovalRequest(db, parsed.value, id.orgId); if (!result.success) return res.status(404).json({ error: result.error }); return res.json({ success: true, request: result.request }); } catch (err) { return res.status(500).json({ error: err.message }); } });
    router.post('/:id/approve', async (req, res) => { try { const id = _requireIdentity(req, res); if (!id) return; const parsed = _parseIntParam(req.params.id, 'id'); if (parsed.error) return res.status(400).json({ error: parsed.error }); const vr = validate(req.body, schemas.approve); if (!vr.valid) return res.status(400).json({ error: 'validation_failed', details: vr.errors }); const result = await approvalService.approveApprovalRequest(db, parsed.value, { actor_user_id: id.userId, org_id: id.orgId, reason: req.body.reason || null, metadata: req.body.metadata || {} }); if (!result.success) return _mapError(res, result); return res.json({ success: true, request: result.request, idempotent: result.idempotent || false, message: result.message || 'approved' }); } catch (err) { return res.status(500).json({ error: err.message }); } });
    router.post('/:id/reject', async (req, res) => { try { const id = _requireIdentity(req, res); if (!id) return; const parsed = _parseIntParam(req.params.id, 'id'); if (parsed.error) return res.status(400).json({ error: parsed.error }); const vr = validate(req.body, schemas.reject); if (!vr.valid) return res.status(400).json({ error: 'validation_failed', details: vr.errors }); const result = await approvalService.rejectApprovalRequest(db, parsed.value, { actor_user_id: id.userId, org_id: id.orgId, reason: req.body.reason || null, metadata: req.body.metadata || {} }); if (!result.success) return _mapError(res, result); return res.json({ success: true, request: result.request }); } catch (err) { return res.status(500).json({ error: err.message }); } });
    router.post('/:id/cancel', async (req, res) => { try { const id = _requireIdentity(req, res); if (!id) return; const parsed = _parseIntParam(req.params.id, 'id'); if (parsed.error) return res.status(400).json({ error: parsed.error }); const vr = validate(req.body, schemas.cancel); if (!vr.valid) return res.status(400).json({ error: 'validation_failed', details: vr.errors }); const result = await approvalService.cancelApprovalRequest(db, parsed.value, { actor_user_id: id.userId, org_id: id.orgId, reason: req.body.reason || null, metadata: req.body.metadata || {} }); if (!result.success) return _mapError(res, result); return res.json({ success: true, request: result.request }); } catch (err) { return res.status(500).json({ error: err.message }); } });
    return router;
}
module.exports = createApprovalRoutes;
