'use strict';
const express = require('express');
const executionService = require('../services/workflow-execution-service');
const { validate } = require('../common/validate');
const schemas = require('../schemas/workflows');
function _requireIdentity(req, res) { if (!req.identity || !req.identity.userId) { res.status(401).json({ error: 'actor_user_id_not_in_trusted_context' }); return null; } if (!req.identity.orgId) { res.status(401).json({ error: 'org_id_not_in_trusted_context' }); return null; } return req.identity; }
function _parseId(val) { const n = parseInt(val, 10); return (isNaN(n) || n < 1) ? null : n; }
function _clampPagination(query) { let limit = parseInt(query.limit, 10); let offset = parseInt(query.offset, 10); if (isNaN(limit) || limit < 1) limit = 50; if (limit > 200) limit = 200; if (isNaN(offset) || offset < 0) offset = 0; return { limit, offset }; }
function createWorkflowRoutes(db) {
    if (!db) throw new Error('[workflows] FATAL: db required — fail closed');
    const router = express.Router();
    router.post('/:id/execute', async (req, res) => { try { const id = _requireIdentity(req, res); if (!id) return; const vr = validate(req.body, schemas.execute); if (!vr.valid) return res.status(400).json({ error: 'validation_failed', details: vr.errors }); const result = await executionService.executeWorkflow(db, { org_id: id.orgId, workflow_id: req.params.id, actor_user_id: id.userId, action_type: vr.cleaned.action_type || 'execute', is_bulk: !!vr.cleaned.is_bulk, is_ai_originated: !!vr.cleaned.is_ai_originated, is_destructive: !!vr.cleaned.is_destructive, payload: vr.cleaned.payload || {} }); if (!result.success && result.execution_status === 'BLOCKED_ERROR') return res.status(422).json(result); if (!result.success) return res.status(400).json(result); return res.status(result.execution_status === 'EXECUTED' ? 200 : 202).json(result); } catch (err) { return res.status(500).json({ error: err.message }); } });
    router.post('/:id/replay', async (req, res) => { try { const id = _requireIdentity(req, res); if (!id) return; const executionId = _parseId(req.params.id); if (!executionId) return res.status(400).json({ error: 'invalid_execution_id' }); const result = await executionService.replayApprovedExecution(db, { org_id: id.orgId, execution_id: executionId, actor_user_id: id.userId }); if (!result.success) { if (result.error === 'execution_not_found') return res.status(404).json(result); if (result.error === 'replay_already_executed') return res.status(409).json(result); if (typeof result.error === 'string' && result.error.startsWith('approval_not_approved')) return res.status(403).json(result); return res.status(400).json(result); } return res.json(result); } catch (err) { return res.status(500).json({ error: err.message }); } });
    router.get('/executions', async (req, res) => { try { const id = _requireIdentity(req, res); if (!id) return; const pg = _clampPagination(req.query); const result = await await executionService.listExecutions(db, { org_id: id.orgId, workflow_id: req.query.workflow_id || undefined, execution_status: req.query.status || undefined, limit: pg.limit, offset: pg.offset }); if (!result.success) return res.status(500).json({ error: result.error }); return res.json({ success: true, executions: result.executions, total: result.total, limit: pg.limit, offset: pg.offset }); } catch (err) { return res.status(500).json({ error: err.message }); } });
    router.get('/executions/:id', async (req, res) => { try { const id = _requireIdentity(req, res); if (!id) return; const execId = _parseId(req.params.id); if (!execId) return res.status(400).json({ error: 'invalid_execution_id' }); const result = await executionService.getExecution(db, execId, id.orgId); if (!result.success) return res.status(404).json({ error: result.error }); return res.json({ success: true, execution: result.execution }); } catch (err) { return res.status(500).json({ error: err.message }); } });
    return router;
}
module.exports = createWorkflowRoutes;
